import { component, type ComponentRecord } from './shared.js';
// Registro da categoria "Ações" (pasta components/actions). Um component() por componente, na ordem do menu.
export const actionsRegistry: ComponentRecord[] = [
  component({
    id: 'button', name: 'Button', category: 'Ações',
    description: 'Ação principal de uma tela: primária, secundária, discreta, perigosa ou como link.',
    variants: ['primary', 'secondary', 'ghost', 'danger', 'link', 'sm', 'md', 'lg', 'loading', 'asChild'],
    parts: ['Root'],
    origins: ['Caraminholas · .btn', 'iFIGHT · ui/button.tsx'],
    references: ['Radix Slot', 'PrimeReact Button', 'MUI Button'],
    code: '<Button variant="primary">Salvar alterações</Button>',
  }),
  component({
    id: 'icon-button', name: 'IconButton', category: 'Ações',
    description: 'Botão só com ícone para ações compactas em barras de ferramentas e cartões. aria-label é obrigatório.',
    variants: ['primary', 'secondary', 'ghost', 'danger', 'link', 'round', 'square', 'sm', 'md', 'lg', 'loading'],
    parts: ['Root'],
    origins: ['Few · novo padrão'],
    references: ['MUI IconButton', 'PrimeReact Button (icon-only)'],
    code: '<IconButton aria-label="Fechar">×</IconButton>',
  }),
  component({
    id: 'button-group', name: 'ButtonGroup', category: 'Ações',
    description: 'Agrupa Button/IconButton relacionados com bordas coladas; propaga size e variant por contexto.',
    variants: ['horizontal', 'vertical', 'attached'],
    parts: ['Root'],
    origins: ['Few · novo padrão'],
    references: ['PrimeReact ButtonGroup', 'MUI ButtonGroup'],
    code: '<ButtonGroup><Button>Um</Button><Button>Dois</Button></ButtonGroup>',
  }),
  component({
    id: 'toggle', name: 'Toggle', category: 'Ações',
    description: 'Botão de dois estados (pressionado/solto), como negrito num editor de texto.',
    variants: ['primary', 'secondary', 'sm', 'md', 'lg'],
    parts: ['Root'],
    origins: ['Few · novo padrão'],
    references: ['Radix Toggle', 'MUI ToggleButton'],
    code: '<Toggle defaultPressed>Negrito</Toggle>',
  }),
  component({
    id: 'toggle-group', name: 'ToggleGroup', category: 'Ações',
    description: 'Conjunto de opções alternáveis (seleção única ou múltipla) com navegação por setas.',
    variants: ['single', 'multiple', 'horizontal', 'vertical'],
    parts: ['Root', 'Item'],
    origins: ['Few · novo padrão'],
    references: ['Radix ToggleGroup', 'MUI ToggleButtonGroup'],
    code: '<ToggleGroup type="single" defaultValue="left"><ToggleGroup.Item value="left">Esquerda</ToggleGroup.Item></ToggleGroup>',
  }),
  component({
    id: 'split-button', name: 'SplitButton', category: 'Ações',
    description: 'Ação principal com um gatilho ao lado que abre uma lista de ações secundárias.',
    variants: ['primary', 'secondary', 'sm', 'md', 'lg'],
    parts: ['Root', 'Action', 'Trigger', 'Content', 'Item'],
    origins: ['Few · novo padrão'],
    references: ['PrimeReact SplitButton', 'MUI ButtonGroup + Menu'],
    code: '<SplitButton><SplitButton.Action>Publicar</SplitButton.Action><SplitButton.Trigger /><SplitButton.Content><SplitButton.Item>Salvar como rascunho</SplitButton.Item></SplitButton.Content></SplitButton>',
  }),
  component({
    id: 'link', name: 'Link', category: 'Ações',
    description: 'Link de texto com variantes de cor, sublinhado e indicador de link externo.',
    variants: ['default', 'muted', 'brand', 'always', 'hover', 'none', 'external'],
    parts: ['Root'],
    origins: ['Few · novo padrão'],
    references: ['Radix Slot', 'Next.js Link'],
    code: '<Link href="/painel">Ir para o painel</Link>',
  }),
];
