import { component, type ComponentRecord } from './shared.js';
// Registro da categoria "Dados" (pasta components/data). Um component() por componente, na ordem do menu.
export const dataRegistry: ComponentRecord[] = [
  component({
    id: 'table', name: 'Table', category: 'Dados',
    description: 'Tabela acessível com rolagem horizontal, densidade, zebra e cabeçalho fixo opcionais.',
    variants: ['compact', 'comfortable', 'striped', 'cabeçalho fixo', 'coluna ordenável'],
    parts: ['Root', 'Caption', 'Header', 'Body', 'Footer', 'Row', 'Head', 'Cell', 'Empty'],
    origins: ['Few · novo padrão'],
    references: ['Radix (padrão de composição)', 'MUI Table'],
    code: '<Table.Root striped>\n  <Table.Caption>Pedidos recentes</Table.Caption>\n  <Table.Header><Table.Row><Table.Head scope="col">Cliente</Table.Head></Table.Row></Table.Header>\n  <Table.Body><Table.Row><Table.Cell>Ana Lima</Table.Cell></Table.Row></Table.Body>\n</Table.Root>',
  }),
  component({
    id: 'data-table', name: 'DataTable', category: 'Dados',
    description: 'Atalho orientado a dados sobre o Table: colunas, ordenação e seleção por checkbox.',
    variants: ['ordenação por coluna', 'seleção múltipla', 'estado vazio'],
    parts: [],
    origins: ['Caraminholas · pedidos', 'iFIGHT · alunos'],
    references: ['MUI DataGrid', 'PrimeReact DataTable'],
    code: '<DataTable caption="Pedidos" rowKey={row => row.id}\n  columns={[{ key: "id", label: "Pedido", render: row => row.id, sortable: true }]}\n  rows={pedidos} />',
  }),
  component({
    id: 'list', name: 'List', category: 'Dados',
    description: 'Lista com item, ícone, título, descrição e ação — simples, dividida ou em cartão.',
    variants: ['plain', 'divided', 'card', 'interativa'],
    parts: ['Root', 'Item', 'ItemIcon', 'ItemContent', 'ItemTitle', 'ItemDescription', 'ItemAction'],
    origins: ['Few · novo padrão'],
    references: ['MUI List'],
    code: '<List variant="divided">\n  <List.Item>\n    <List.ItemContent><List.ItemTitle>Ana Lima</List.ItemTitle><List.ItemDescription>Aluna desde 2024</List.ItemDescription></List.ItemContent>\n  </List.Item>\n</List>',
  }),
  component({
    id: 'description-list', name: 'DescriptionList', category: 'Dados',
    description: 'Pares de termo e detalhe, em layout vertical ou horizontal, com colunas opcionais.',
    variants: ['vertical', 'horizontal', 'colunas'],
    parts: ['Root', 'Item', 'Term', 'Details'],
    origins: ['Few · novo padrão'],
    references: ['MDN <dl>', 'GOV.UK Design System summary list'],
    code: '<DescriptionList layout="horizontal">\n  <DescriptionList.Item><DescriptionList.Term>Plano</DescriptionList.Term><DescriptionList.Details>Mensal</DescriptionList.Details></DescriptionList.Item>\n</DescriptionList>',
  }),
  component({
    id: 'avatar', name: 'Avatar', category: 'Dados',
    description: 'Foto de perfil com iniciais de reserva e indicador de presença.',
    variants: ['sm', 'md', 'lg', 'xl', 'circle', 'square'],
    parts: ['Root', 'Image', 'Fallback', 'Status'],
    origins: ['iFIGHT · alunos'],
    references: ['Radix Avatar'],
    code: '<Avatar.Root name="Ana Lima">\n  <Avatar.Image src="/ana.jpg" />\n  <Avatar.Fallback />\n  <Avatar.Status status="online" />\n</Avatar.Root>',
  }),
  component({
    id: 'avatar-group', name: 'AvatarGroup', category: 'Dados',
    description: 'Empilha avatares e mostra um contador "+N" quando passa do limite.',
    variants: ['max', 'espaçamento'],
    parts: ['Root', 'Overflow'],
    origins: ['Few · novo padrão'],
    references: ['Radix Avatar (composição)', 'MUI AvatarGroup'],
    code: '<AvatarGroup.Root max={3}>\n  <Avatar.Root name="Ana Lima"><Avatar.Fallback /></Avatar.Root>\n  <Avatar.Root name="João Santos"><Avatar.Fallback /></Avatar.Root>\n  <AvatarGroup.Overflow />\n</AvatarGroup.Root>',
  }),
  component({
    id: 'stat', name: 'Stat', category: 'Dados',
    description: 'Indicador numérico com rótulo, variação e descrição. Substitui o MetricCard.',
    variants: ['neutral', 'success', 'warning', 'danger', 'info'],
    parts: ['Root', 'Label', 'Value', 'Change', 'Description', 'Icon'],
    origins: ['iFIGHT · Visão da Academia'],
    references: ['MUI Card + Typography'],
    code: '<Stat tone="success">\n  <Stat.Label>Alunos ativos</Stat.Label>\n  <Stat.Value>148</Stat.Value>\n  <Stat.Change direction="up">8 novas matrículas</Stat.Change>\n</Stat>',
  }),
  component({
    id: 'timeline', name: 'Timeline', category: 'Dados',
    description: 'Sequência de eventos com indicador, conector e horário — vertical, horizontal ou alternada.',
    variants: ['vertical', 'horizontal', 'alternada'],
    parts: ['Root', 'Item', 'Indicator', 'Connector', 'Content', 'Title', 'Time', 'Description'],
    origins: ['Few · novo padrão'],
    references: ['PrimeReact Timeline', 'MUI Timeline'],
    code: '<Timeline>\n  <Timeline.Item state="complete">\n    <Timeline.Indicator />\n    <Timeline.Content><Timeline.Title>Pedido confirmado</Timeline.Title><Timeline.Time dateTime="2026-09-20">20 de set.</Timeline.Time></Timeline.Content>\n  </Timeline.Item>\n</Timeline>',
  }),
  component({
    id: 'tree', name: 'Tree', category: 'Dados',
    description: 'Árvore navegável por teclado (setas, Home/End, digitação) com seleção e expansão.',
    variants: ['seleção única', 'seleção múltipla', 'expansão controlada'],
    parts: ['Root', 'Item', 'ItemTrigger', 'ItemContent'],
    origins: ['Few · novo padrão'],
    references: ['WAI-ARIA APG Tree View', 'PrimeReact Tree'],
    code: '<Tree defaultExpanded={["pastas"]}>\n  <Tree.Item value="pastas">\n    <Tree.ItemTrigger>Pastas</Tree.ItemTrigger>\n    <Tree.ItemContent><Tree.Item value="contratos"><Tree.ItemTrigger>Contratos</Tree.ItemTrigger></Tree.Item></Tree.ItemContent>\n  </Tree.Item>\n</Tree>',
  }),
  component({
    id: 'accordion', name: 'Accordion', category: 'Dados',
    description: 'Painéis expansíveis com roving focus e animação respeitando movimento reduzido.',
    variants: ['single', 'multiple', 'collapsible'],
    parts: ['Root', 'Item', 'Header', 'Trigger', 'Content'],
    origins: ['Few · novo padrão'],
    references: ['Radix Accordion'],
    code: '<Accordion type="single" collapsible defaultValue="faq-1">\n  <Accordion.Item value="faq-1">\n    <Accordion.Header><Accordion.Trigger>Como funciona o plano?</Accordion.Trigger></Accordion.Header>\n    <Accordion.Content>Cobrança mensal, sem fidelidade.</Accordion.Content>\n  </Accordion.Item>\n</Accordion>',
  }),
  component({
    id: 'collapsible', name: 'Collapsible', category: 'Dados',
    description: 'Par trigger/conteúdo simples para mostrar e esconder um bloco.',
    variants: ['open', 'defaultOpen', 'disabled'],
    parts: ['Root', 'Trigger', 'Content'],
    origins: ['Few · novo padrão'],
    references: ['Radix Collapsible'],
    code: '<Collapsible defaultOpen={false}>\n  <Collapsible.Trigger>Ver detalhes técnicos</Collapsible.Trigger>\n  <Collapsible.Content>Node 20, PostgreSQL 15, Redis 7.</Collapsible.Content>\n</Collapsible>',
  }),
  component({
    id: 'carousel', name: 'Carousel', category: 'Dados',
    description: 'Trilho com scroll-snap, teclado ←→ e indicadores — para destaques e depoimentos.',
    variants: ['loop', 'align start', 'align center', 'horizontal', 'vertical'],
    parts: ['Root', 'Viewport', 'Content', 'Item', 'Previous', 'Next', 'Indicators'],
    origins: ['Few · novo padrão'],
    references: ['Radix (padrão de composição)', 'MUI Stepper/Carousel patterns'],
    code: '<Carousel loop>\n  <Carousel.Viewport><Carousel.Content><Carousel.Item>1</Carousel.Item><Carousel.Item>2</Carousel.Item></Carousel.Content></Carousel.Viewport>\n  <Carousel.Previous>‹</Carousel.Previous><Carousel.Next>›</Carousel.Next>\n  <Carousel.Indicators />\n</Carousel>',
  }),
];
