import { component, type ComponentRecord } from './shared.js';
// Registro da categoria "Feedback" (pasta components/feedback). Um component() por componente, na ordem do menu.
export const feedbackRegistry: ComponentRecord[] = [
  component({
    id: 'alert', name: 'Alert', category: 'Feedback',
    description: 'Aviso inline com tom semântico, ícone, título, descrição, ação e fechamento opcional.',
    variants: ['tone: neutral | success | warning | danger | info', 'variant: soft | outline', 'role=alert (danger) | role=status (demais)'],
    parts: ['Root', 'Icon', 'Title', 'Description', 'Action', 'Close'],
    origins: ['Caraminholas · feedback de checkout', 'iFIGHT · cards de status'],
    references: ['Radix (padrão de composição)', 'PrimeReact Message'],
    code: '<Alert tone="success"><Alert.Icon /><Alert.Title>Salvo</Alert.Title><Alert.Description>Suas alterações foram salvas.</Alert.Description><Alert.Close onDismiss={() => {}} /></Alert>',
  }),
  component({
    id: 'badge', name: 'Badge', category: 'Feedback',
    description: 'Rótulo pequeno de status ou contagem, com tom, variante e bolinha opcional.',
    variants: ['variant: solid | soft | outline', 'size: sm | md', 'dot'],
    parts: [],
    origins: ['Caraminholas · .chip', 'iFIGHT · ui/badge.tsx'],
    references: ['Radix Badge', 'PrimeReact Tag'],
    code: '<Badge tone="success" dot>Ativo</Badge>',
  }),
  component({
    id: 'tag', name: 'Tag', category: 'Feedback',
    description: 'Chip com rótulo, ícone opcional e botão de remover — para filtros e seleções múltiplas.',
    variants: ['variant: solid | soft | outline', 'size: sm | md', 'interactive (com onClick)', 'removable (com Tag.Close)'],
    parts: ['Root', 'Label', 'Icon', 'Close'],
    origins: ['Few · novo padrão'],
    references: ['PrimeReact Chip', 'MUI Chip'],
    code: '<Tag><Tag.Label>React</Tag.Label><Tag.Close label="React" onRemove={() => {}} /></Tag>',
  }),
  component({
    id: 'progress', name: 'Progress', category: 'Feedback',
    description: 'Barra de progresso linear, determinada ou indeterminada, com rótulo e valor.',
    variants: ['determinate (value)', 'indeterminate (value={null})', 'size: sm | md | lg'],
    parts: ['Root', 'Track', 'Indicator', 'Label', 'Value'],
    origins: ['iFIGHT · progressão'],
    references: ['Radix Progress'],
    code: '<Progress value={72}><Progress.Label>Perfil</Progress.Label><Progress.Track><Progress.Indicator /></Progress.Track><Progress.Value /></Progress>',
  }),
  component({
    id: 'progress-circle', name: 'Progress Circle', category: 'Feedback',
    description: 'Progresso circular em SVG, determinado ou indeterminado, com rótulo central opcional.',
    variants: ['determinate (value)', 'indeterminate (value={null})', 'size: sm | md | lg | número (px)'],
    parts: ['Root', 'Circle', 'Label'],
    origins: ['Few · novo padrão'],
    references: ['MUI CircularProgress', 'Radix (padrão de composição)'],
    code: '<ProgressCircle value={72}><ProgressCircle.Circle /><ProgressCircle.Label /></ProgressCircle>',
  }),
  component({
    id: 'spinner', name: 'Spinner', category: 'Feedback',
    description: 'Indicador de carregamento giratório com anúncio sr-only para leitores de tela.',
    variants: ['size: sm | md | lg', 'tone'],
    parts: [],
    origins: ['Few · novo padrão'],
    references: ['Radix (padrão de composição)', 'PrimeReact ProgressSpinner'],
    code: '<Spinner label="Carregando pedidos" />',
  }),
  component({
    id: 'skeleton', name: 'Skeleton', category: 'Feedback',
    description: 'Placeholder de carregamento: linhas de texto, círculo, retângulo, ou o próprio conteúdo escondido.',
    variants: ['variant: text | circle | rect', 'lines', 'asChild (envolve e esconde o conteúdo real)'],
    parts: [],
    origins: ['Few · novo padrão'],
    references: ['Radix (padrão de composição)'],
    code: '<Skeleton variant="text" lines={3} />',
  }),
  component({
    id: 'empty-state', name: 'Empty State', category: 'Feedback',
    description: 'Estado vazio com ícone, título, descrição e ações — para listas, buscas e caixas sem conteúdo.',
    variants: ['size: sm | md | lg'],
    parts: ['Root', 'Icon', 'Title', 'Description', 'Actions'],
    origins: ['Caraminholas · sacola vazia'],
    references: ['Radix (padrão de composição)'],
    code: '<EmptyState><EmptyState.Icon /><EmptyState.Title>Nada por aqui</EmptyState.Title><EmptyState.Description>Crie o primeiro projeto para começar.</EmptyState.Description><EmptyState.Actions><button className="few-button few-button--primary">Novo projeto</button></EmptyState.Actions></EmptyState>',
  }),
];
