import { component, type ComponentRecord } from './shared.js';
// Registro da categoria "Formulários" (pasta components/forms). Um component() por componente, na ordem do menu.
export const formsRegistry: ComponentRecord[] = [
  component({
    id: 'form', name: 'Form', category: 'Formulários',
    description: 'Formulário nativo cujo onSubmit já entrega os valores prontos (via FormData), sem precisar ler cada input.',
    variants: ['com validação nativa (noValidate=false)', 'submit via asChild'],
    parts: ['Root', 'Submit'],
    origins: ['Few · novo padrão'],
    references: ['Radix Form', 'MUI Form'],
    code: '<Form onSubmit={(e, values) => console.log(values)}>\n  <Field>…</Field>\n  <Form.Submit>Enviar</Form.Submit>\n</Form>',
  }),
  component({
    id: 'fieldset', name: 'Fieldset', category: 'Formulários',
    description: 'Agrupa campos relacionados com legenda semântica; disabled no grupo propaga para todos os controles.',
    variants: ['habilitado', 'disabled (propaga)'],
    parts: ['Root', 'Legend'],
    origins: ['Few · novo padrão'],
    references: ['HTML fieldset/legend', 'PrimeReact Fieldset'],
    code: '<Fieldset>\n  <Fieldset.Legend>Endereço</Fieldset.Legend>\n  <Field>…</Field>\n</Fieldset>',
  }),
  component({
    id: 'field', name: 'Field', category: 'Formulários',
    description: 'Liga label, controle, descrição e erro automaticamente: ids, aria-describedby e aria-invalid saem prontos.',
    variants: ['com descrição', 'inválido com erro', 'obrigatório'],
    parts: ['Root', 'Label', 'Control', 'Description', 'Error'],
    origins: ['Caraminholas · .field'],
    references: ['Radix Form.Field', 'MUI FormControl', 'PrimeReact FloatLabel'],
    code: '<Field invalid={!!error}>\n  <Field.Label>E-mail</Field.Label>\n  <Field.Control><Input type="email" /></Field.Control>\n  <Field.Error>{error}</Field.Error>\n</Field>',
  }),
  component({
    id: 'label', name: 'Label', category: 'Formulários',
    description: 'Rótulo de campo com asChild e indicador opcional de obrigatoriedade.',
    variants: ['padrão', 'obrigatório (required)'],
    parts: ['Root'],
    origins: ['Few · novo padrão'],
    references: ['Radix Label'],
    code: '<Label htmlFor="nome" required>Nome</Label>',
  }),
  component({
    id: 'input', name: 'Input', category: 'Formulários',
    description: 'Campo de texto nativo com tamanhos e estado inválido.',
    variants: ['sm', 'md', 'lg', 'inválido'],
    parts: [],
    origins: ['Caraminholas · .field'],
    references: ['MUI TextField', 'PrimeReact InputText'],
    code: '<Input placeholder="Seu nome" />',
  }),
  component({
    id: 'input-group', name: 'InputGroup', category: 'Formulários',
    description: 'Une prefixo, sufixo, ícone e input numa borda única, como em campos de valor monetário ou busca.',
    variants: ['addon textual', 'elemento/ícone', 'inválido'],
    parts: ['Root', 'Addon', 'Element', 'Input'],
    origins: ['Few · novo padrão'],
    references: ['MUI InputAdornment', 'Mantine Input.Section'],
    code: '<InputGroup>\n  <InputGroup.Addon>R$</InputGroup.Addon>\n  <InputGroup.Input placeholder="0,00" />\n</InputGroup>',
  }),
  component({
    id: 'textarea', name: 'Textarea', category: 'Formulários',
    description: 'Área de texto multi-linha, com opção de crescer junto com o conteúdo.',
    variants: ['fixa (rows)', 'autoResize', 'inválido'],
    parts: [],
    origins: ['Caraminholas · FormRow'],
    references: ['MUI TextField multiline', 'PrimeReact Textarea'],
    code: '<Textarea placeholder="Conte mais…" autoResize />',
  }),
  component({
    id: 'number-input', name: 'NumberInput', category: 'Formulários',
    description: 'Campo numérico com setas de incremento/decremento, teclado completo e limites min/max/step.',
    variants: ['com min/max', 'com step decimal'],
    parts: ['Root', 'Input', 'Increment', 'Decrement'],
    origins: ['Few · novo padrão'],
    references: ['Radix NumberField (Ark UI)', 'PrimeReact InputNumber'],
    code: '<NumberInput defaultValue={1} min={0} max={10}>\n  <NumberInput.Decrement>−</NumberInput.Decrement>\n  <NumberInput.Input />\n  <NumberInput.Increment>+</NumberInput.Increment>\n</NumberInput>',
  }),
  component({
    id: 'password-input', name: 'PasswordInput', category: 'Formulários',
    description: 'Campo de senha com botão para mostrar/ocultar o valor digitado.',
    variants: ['oculto (padrão)', 'visível'],
    parts: ['Root', 'Input', 'Toggle'],
    origins: ['Few · novo padrão'],
    references: ['PrimeReact Password', 'Mantine PasswordInput'],
    code: '<PasswordInput>\n  <PasswordInput.Input placeholder="Senha" />\n  <PasswordInput.Toggle />\n</PasswordInput>',
  }),
  component({
    id: 'pin-input', name: 'PinInput', category: 'Formulários',
    description: 'Código de verificação em caixas separadas, com colagem distribuindo os dígitos automaticamente.',
    variants: ['numérico', 'mascarado (mask)'],
    parts: ['Root', 'Input'],
    origins: ['Few · novo padrão'],
    references: ['Chakra PinInput', 'Ark UI PinInput'],
    code: '<PinInput length={4} onComplete={console.log}>\n  {Array.from({ length: 4 }).map((_, i) => <PinInput.Input key={i} index={i} />)}\n</PinInput>',
  }),
  component({
    id: 'native-select', name: 'NativeSelect', category: 'Formulários',
    description: 'Select nativo (melhor suporte mobile) com chevron consistente com os outros campos.',
    variants: ['sm', 'md', 'lg', 'inválido'],
    parts: [],
    origins: ['Caraminholas · OrderForm'],
    references: ['MUI NativeSelect', 'PrimeReact Dropdown'],
    code: '<NativeSelect defaultValue="sp">\n  <option value="sp">São Paulo</option>\n  <option value="rj">Rio de Janeiro</option>\n</NativeSelect>',
  }),
  component({
    id: 'checkbox', name: 'Checkbox', category: 'Formulários',
    description: 'Checkbox acessível com estado indeterminado, sobre um input nativo visualmente oculto.',
    variants: ['marcado', 'desmarcado', 'indeterminado'],
    parts: ['Root', 'Indicator'],
    origins: ['Caraminholas · configurações'],
    references: ['Radix Checkbox', 'MUI Checkbox'],
    code: '<Checkbox.Root checked={checked} onCheckedChange={setChecked}>\n  <Checkbox.Indicator />\n  Aceito os termos\n</Checkbox.Root>',
  }),
  component({
    id: 'checkbox-group', name: 'CheckboxGroup', category: 'Formulários',
    description: 'Conjunto de checkboxes que compartilham uma lista de valores selecionados.',
    variants: ['vertical', 'horizontal'],
    parts: ['Root', 'Item'],
    origins: ['Caraminholas · configurações'],
    references: ['Ark UI CheckboxGroup', 'Mantine Checkbox.Group'],
    code: '<CheckboxGroup value={value} onValueChange={setValue}>\n  <CheckboxGroup.Item value="a"><Checkbox.Indicator /> A</CheckboxGroup.Item>\n  <CheckboxGroup.Item value="b"><Checkbox.Indicator /> B</CheckboxGroup.Item>\n</CheckboxGroup>',
  }),
  component({
    id: 'radio-group', name: 'RadioGroup', category: 'Formulários',
    description: 'Seleção única com navegação por setas entre as opções, como o grupo nativo de radios.',
    variants: ['vertical', 'horizontal'],
    parts: ['Root', 'Item', 'Indicator'],
    origins: ['Few · novo padrão'],
    references: ['Radix RadioGroup', 'MUI RadioGroup'],
    code: '<RadioGroup value={value} onValueChange={setValue}>\n  <RadioGroup.Item value="a"><RadioGroup.Indicator /> A</RadioGroup.Item>\n  <RadioGroup.Item value="b"><RadioGroup.Indicator /> B</RadioGroup.Item>\n</RadioGroup>',
  }),
  component({
    id: 'switch', name: 'Switch', category: 'Formulários',
    description: 'Alternador on/off com role=switch, usado em preferências e configurações rápidas.',
    variants: ['sm', 'md', 'lg'],
    parts: ['Root', 'Thumb'],
    origins: ['iFIGHT · preferências'],
    references: ['Radix Switch', 'MUI Switch'],
    code: '<Switch.Root checked={on} onCheckedChange={setOn}>\n  <Switch.Thumb />\n</Switch.Root>',
  }),
  component({
    id: 'slider', name: 'Slider', category: 'Formulários',
    description: 'Faixa de valores com um ou dois cursores, arrastável e navegável por teclado.',
    variants: ['valor único', 'faixa (2 thumbs)', 'vertical'],
    parts: ['Root', 'Track', 'Range', 'Thumb'],
    origins: ['Few · novo padrão'],
    references: ['Radix Slider', 'MUI Slider'],
    code: '<Slider defaultValue={[30]} max={100} step={5}>\n  <Slider.Track>\n    <Slider.Range />\n    <Slider.Thumb index={0} />\n  </Slider.Track>\n</Slider>',
  }),
  component({
    id: 'rating', name: 'Rating', category: 'Formulários',
    description: 'Avaliação por estrelas com teclado e modo somente leitura para exibir uma nota.',
    variants: ['editável', 'readOnly'],
    parts: ['Root', 'Item'],
    origins: ['Few · novo padrão'],
    references: ['PrimeReact Rating', 'MUI Rating'],
    code: '<Rating defaultValue={3} max={5}>\n  {Array.from({ length: 5 }).map((_, i) => <Rating.Item key={i} value={i + 1} />)}\n</Rating>',
  }),
  component({
    id: 'file-upload', name: 'FileUpload', category: 'Formulários',
    description: 'Envio de arquivos por clique ou arrastar-e-soltar, com validação de tipo/tamanho e lista de selecionados.',
    variants: ['clique', 'arrastar e soltar', 'múltiplos arquivos'],
    parts: ['Root', 'Dropzone', 'Trigger', 'HiddenInput', 'List', 'Item', 'ItemName', 'ItemSize', 'ItemDelete'],
    origins: ['Few · novo padrão'],
    references: ['Ark UI FileUpload', 'Mantine FileInput'],
    code: '<FileUpload accept="image/*" maxSize={5_000_000} onFilesChange={setFiles}>\n  <FileUpload.Dropzone>\n    <FileUpload.Trigger>Escolher arquivo</FileUpload.Trigger>\n    <FileUpload.HiddenInput />\n  </FileUpload.Dropzone>\n</FileUpload>',
  }),
  component({
    id: 'tags-input', name: 'TagsInput', category: 'Formulários',
    description: 'Lista de tags digitadas com Enter ou vírgula, com limite máximo e remoção individual.',
    variants: ['sem duplicadas (padrão)', 'com limite máximo'],
    parts: ['Root', 'Label', 'Item', 'ItemDelete', 'Input'],
    origins: ['Few · novo padrão'],
    references: ['Ark UI TagsInput', 'Mantine TagsInput'],
    code: '<TagsInput value={tags} onValueChange={setTags} max={5}>\n  {tags.map((tag, i) => <TagsInput.Item key={tag} index={i}><TagsInput.ItemDelete /></TagsInput.Item>)}\n  <TagsInput.Input placeholder="Adicionar…" />\n</TagsInput>',
  }),
];
