import { component, type ComponentRecord } from './shared.js';
// Registro da categoria "Navegação" (pasta components/navigation). Um component() por componente, na ordem do menu.
export const navigationRegistry: ComponentRecord[] = [
  component({
    id: 'tabs', name: 'Tabs', category: 'Navegação',
    description: 'Alterna entre painéis de conteúdo relacionados sem trocar de página.',
    variants: ['horizontal', 'vertical', 'manual activation'],
    parts: ['Root', 'List', 'Trigger', 'Content'],
    origins: ['iFIGHT · navegação de painéis'],
    references: ['Radix Tabs', 'PrimeReact TabView'],
    code: '<Tabs defaultValue="geral"><Tabs.List><Tabs.Trigger value="geral">Visão geral</Tabs.Trigger><Tabs.Trigger value="atividade">Atividade</Tabs.Trigger></Tabs.List><Tabs.Content value="geral">…</Tabs.Content><Tabs.Content value="atividade">…</Tabs.Content></Tabs>',
  }),
  component({
    id: 'breadcrumb', name: 'Breadcrumb', category: 'Navegação',
    description: 'Mostra o caminho até a página atual e permite voltar a qualquer nível.',
    variants: ['com reticências', 'link asChild para o Link do Next'],
    parts: ['Root', 'List', 'Item', 'Link', 'Page', 'Separator', 'Ellipsis'],
    origins: ['Few · novo padrão'],
    references: ['shadcn/ui Breadcrumb', 'WAI-ARIA APG Breadcrumb'],
    code: '<Breadcrumb><Breadcrumb.List><Breadcrumb.Item><Breadcrumb.Link href="/">Início</Breadcrumb.Link></Breadcrumb.Item><Breadcrumb.Separator /><Breadcrumb.Item><Breadcrumb.Page>Projeto</Breadcrumb.Page></Breadcrumb.Item></Breadcrumb.List></Breadcrumb>',
  }),
  component({
    id: 'pagination', name: 'Pagination', category: 'Navegação',
    description: 'Divide listas longas em páginas navegáveis por teclado e mouse.',
    variants: ['controlada por total e siblings', 'composição manual'],
    parts: ['Root', 'List', 'Item', 'Link', 'Previous', 'Next', 'Ellipsis'],
    origins: ['Few · novo padrão'],
    references: ['shadcn/ui Pagination'],
    code: '<Pagination page={page} onPageChange={setPage} total={12}><Pagination.Previous /><Pagination.List /><Pagination.Next /></Pagination>',
  }),
  component({
    id: 'steps', name: 'Steps', category: 'Navegação',
    description: 'Guia o usuário por um processo em etapas, mostrando o que já foi concluído.',
    variants: ['clicável', 'horizontal', 'vertical'],
    parts: ['Root', 'Item', 'Indicator', 'Title', 'Description', 'Separator'],
    origins: ['Few · novo padrão'],
    references: ['Ant Design Steps'],
    code: '<Steps value={step} onValueChange={setStep}><Steps.Item index={0}><Steps.Indicator /><Steps.Title>Dados</Steps.Title></Steps.Item><Steps.Separator /><Steps.Item index={1}><Steps.Indicator /><Steps.Title>Pagamento</Steps.Title></Steps.Item></Steps>',
  }),
  component({
    id: 'navigation-menu', name: 'NavigationMenu', category: 'Navegação',
    description: 'Menu de navegação com submenus em flyout, acessível por teclado e mouse.',
    variants: ['flyout por hover', 'flyout por foco/Enter'],
    parts: ['Root', 'List', 'Item', 'Trigger', 'Content', 'Link', 'Indicator'],
    origins: ['Few · novo padrão'],
    references: ['Radix Navigation Menu'],
    code: '<NavigationMenu><NavigationMenu.List><NavigationMenu.Item value="produto"><NavigationMenu.Trigger>Produto</NavigationMenu.Trigger><NavigationMenu.Content><NavigationMenu.Link href="/a">Produto A</NavigationMenu.Link></NavigationMenu.Content></NavigationMenu.Item></NavigationMenu.List></NavigationMenu>',
  }),
  component({
    id: 'sidebar', name: 'Sidebar', category: 'Navegação',
    description: 'Navegação lateral colapsável, com versão off-canvas para telas pequenas.',
    variants: ['collapsible icon', 'collapsible offcanvas', 'side left/right'],
    parts: ['Root', 'Header', 'Content', 'Footer', 'Group', 'GroupLabel', 'Menu', 'MenuItem', 'MenuButton', 'MenuBadge', 'Separator', 'Trigger', 'Rail'],
    origins: ['Catálogo Few · sidebar'],
    references: ['shadcn/ui Sidebar'],
    code: '<Sidebar collapsible="icon"><Sidebar.Header><Sidebar.Trigger /></Sidebar.Header><Sidebar.Content><Sidebar.Group><Sidebar.GroupLabel>Menu</Sidebar.GroupLabel><Sidebar.Menu><Sidebar.MenuItem><Sidebar.MenuButton isActive>Visão geral</Sidebar.MenuButton></Sidebar.MenuItem></Sidebar.Menu></Sidebar.Group></Sidebar.Content></Sidebar>',
  }),
  component({
    id: 'command-menu', name: 'CommandMenu', category: 'Navegação',
    description: 'Paleta de comandos com busca instantânea, ativada por atalho de teclado.',
    variants: ['atalho Ctrl/Cmd+K', 'filtro sem acento'],
    parts: ['Root', 'Input', 'List', 'Group', 'GroupHeading', 'Item', 'Empty', 'Separator', 'Shortcut'],
    origins: ['Catálogo Few · busca "/"'],
    references: ['cmdk', 'shadcn/ui Command'],
    code: '<CommandMenu open={open} onOpenChange={setOpen} shortcut><CommandMenu.Input placeholder="Buscar…" /><CommandMenu.List><CommandMenu.Empty>Nada encontrado.</CommandMenu.Empty><CommandMenu.Item value="Novo projeto" onSelect={criar}>Novo projeto</CommandMenu.Item></CommandMenu.List></CommandMenu>',
  }),
];
