import { component, type ComponentRecord } from './shared.js';
// Registro da categoria "Overlays" (pasta components/overlays). Um component() por componente, na ordem do menu.
export const overlaysRegistry: ComponentRecord[] = [
  component({
    id: 'dialog', name: 'Dialog', category: 'Overlays',
    description: 'Janela modal sobre <dialog> nativo: foco preso, Escape fecha, foco volta ao gatilho.',
    variants: ['sm', 'md', 'lg', 'full'],
    parts: ['Root', 'Trigger', 'Content', 'Title', 'Description', 'Close'],
    origins: ['Caraminholas · StageDialog'],
    references: ['Radix Dialog', 'MUI Dialog'],
    code: '<Dialog><Dialog.Trigger asChild><Button>Abrir</Button></Dialog.Trigger><Dialog.Content size="md"><Dialog.Title>Título</Dialog.Title><Dialog.Description>Descrição.</Dialog.Description><Dialog.Close asChild><Button variant="ghost">Fechar</Button></Dialog.Close></Dialog.Content></Dialog>',
  }),
  component({
    id: 'alert-dialog', name: 'AlertDialog', category: 'Overlays',
    description: 'Confirmação que interrompe o fluxo: só fecha por Cancel, Action ou Escape (nunca clique fora).',
    variants: ['confirmação', 'ação destrutiva'],
    parts: ['Root', 'Trigger', 'Content', 'Title', 'Description', 'Cancel', 'Action'],
    origins: ['Few · novo padrão'],
    references: ['Radix AlertDialog', 'PrimeReact ConfirmDialog'],
    code: '<AlertDialog><AlertDialog.Trigger asChild><Button variant="danger">Excluir</Button></AlertDialog.Trigger><AlertDialog.Content><AlertDialog.Title>Excluir item?</AlertDialog.Title><AlertDialog.Description>Não pode ser desfeito.</AlertDialog.Description><AlertDialog.Cancel asChild><Button variant="secondary">Cancelar</Button></AlertDialog.Cancel><AlertDialog.Action asChild><Button variant="danger">Excluir</Button></AlertDialog.Action></AlertDialog.Content></AlertDialog>',
  }),
  component({
    id: 'drawer', name: 'Drawer', category: 'Overlays',
    description: 'Painel modal que desliza de uma borda da tela (<dialog> nativo), com Handle opcional embaixo.',
    variants: ['left', 'right', 'top', 'bottom'],
    parts: ['Root', 'Trigger', 'Content', 'Title', 'Description', 'Close', 'Handle'],
    origins: ['Few · novo padrão'],
    references: ['Vaul', 'MUI Drawer'],
    code: '<Drawer side="right"><Drawer.Trigger asChild><Button>Filtros</Button></Drawer.Trigger><Drawer.Content><Drawer.Title>Filtros</Drawer.Title><Drawer.Close asChild><Button variant="ghost">Fechar</Button></Drawer.Close></Drawer.Content></Drawer>',
  }),
  component({
    id: 'popover', name: 'Popover', category: 'Overlays',
    description: 'Camada não modal ancorada a um gatilho: popover="manual" + posicionamento automático, sem Portal.',
    variants: ['top', 'bottom', 'left', 'right'],
    parts: ['Root', 'Anchor', 'Trigger', 'Content', 'Close', 'Arrow'],
    origins: ['iFIGHT · painel de ações rápidas'],
    references: ['Radix Popover', 'PrimeReact OverlayPanel'],
    code: '<Popover><Popover.Trigger asChild><Button variant="secondary">Ajustes</Button></Popover.Trigger><Popover.Content side="bottom" align="start"><Popover.Arrow />Conteúdo</Popover.Content></Popover>',
  }),
  component({
    id: 'tooltip', name: 'Tooltip', category: 'Overlays',
    description: 'Dica textual no hover/foco, com delay compartilhado entre vários tooltips via Provider.',
    variants: ['top', 'bottom', 'left', 'right'],
    parts: ['Provider', 'Root', 'Trigger', 'Content', 'Arrow'],
    origins: ['Few · novo padrão'],
    references: ['Radix Tooltip', 'MUI Tooltip'],
    code: '<Tooltip.Provider><Tooltip><Tooltip.Trigger asChild><Button variant="ghost">?</Button></Tooltip.Trigger><Tooltip.Content>Ajuda<Tooltip.Arrow /></Tooltip.Content></Tooltip></Tooltip.Provider>',
  }),
  component({
    id: 'dropdown-menu', name: 'DropdownMenu', category: 'Overlays',
    description: 'Menu acionado por botão: itens, checkbox, radio, atalhos e grupos, com roving focus e typeahead.',
    variants: ['itens', 'checkbox', 'radio', 'com grupos'],
    parts: ['Root', 'Trigger', 'Content', 'Item', 'CheckboxItem', 'RadioGroup', 'RadioItem', 'ItemIndicator', 'Label', 'Group', 'Separator', 'Shortcut'],
    origins: ['iFIGHT · ações da linha da tabela'],
    references: ['Radix DropdownMenu', 'MUI Menu'],
    code: '<DropdownMenu><DropdownMenu.Trigger asChild><Button variant="secondary">Ações</Button></DropdownMenu.Trigger><DropdownMenu.Content><DropdownMenu.Item>Editar</DropdownMenu.Item><DropdownMenu.Separator /><DropdownMenu.Item disabled>Excluir</DropdownMenu.Item></DropdownMenu.Content></DropdownMenu>',
  }),
  component({
    id: 'context-menu', name: 'ContextMenu', category: 'Overlays',
    description: 'Menu na posição do ponteiro (clique direito ou toque longo); reusa o núcleo do DropdownMenu.',
    variants: ['clique direito', 'toque longo'],
    parts: ['Root', 'Trigger', 'Content', 'Item', 'CheckboxItem', 'RadioGroup', 'RadioItem', 'ItemIndicator', 'Label', 'Group', 'Separator', 'Shortcut'],
    origins: ['Few · novo padrão'],
    references: ['Radix ContextMenu'],
    code: '<ContextMenu><ContextMenu.Trigger><div className="demo-surface">Clique com o botão direito</div></ContextMenu.Trigger><ContextMenu.Content><ContextMenu.Item>Copiar</ContextMenu.Item><ContextMenu.Item>Colar</ContextMenu.Item></ContextMenu.Content></ContextMenu>',
  }),
  component({
    id: 'menubar', name: 'Menubar', category: 'Overlays',
    description: 'Barra horizontal de menus (Arquivo, Editar…): roving focus, troca por seta e por hover.',
    variants: ['horizontal'],
    parts: ['Root', 'Menu', 'Trigger', 'Content', 'Item', 'CheckboxItem', 'RadioGroup', 'RadioItem', 'ItemIndicator', 'Label', 'Group', 'Separator', 'Shortcut'],
    origins: ['Few · novo padrão'],
    references: ['Radix Menubar', 'PrimeReact Menubar'],
    code: '<Menubar><Menubar.Menu value="file"><Menubar.Trigger>Arquivo</Menubar.Trigger><Menubar.Content><Menubar.Item>Novo</Menubar.Item></Menubar.Content></Menubar.Menu></Menubar>',
  }),
  component({
    id: 'toast', name: 'Toast', category: 'Overlays',
    description: 'Notificação efêmera em fila: hook useToast() imperativo, pausa no hover/foco, aria-live.',
    variants: ['neutral', 'success', 'warning', 'danger', 'info'],
    parts: ['Provider', 'Viewport', 'Root', 'Title', 'Description', 'Action', 'Close'],
    origins: ['iFIGHT · notificações de partida'],
    references: ['Radix Toast', 'Sonner'],
    code: 'const { toast } = useToast(); <Toast.Provider><Toast.Viewport /></Toast.Provider>; toast({ title: "Salvo", tone: "success" });',
  }),
];
