"use client";
import { useEffect, useRef, useState, type ReactNode } from 'react';
import { HeroVisual } from './hero-visual';
import { Alert, Badge, Button, Card, DataTable, Stat, registry, categories, tokens, LIBRARY_VERSION, type FewTheme, type Tone } from '@fewcompany/ui';
import { demos } from '../demos';
import { VueDemo, hasVueDemo, vueImportLine } from './vue-demo';

type Framework = 'react' | 'vue';

const specialPages = ['overview', 'tokens', 'start', 'apps', 'composition'];
const pageTitles: Record<string, string> = { overview: 'Visão geral', tokens: 'Fundamentos', start: 'Instalação', apps: 'Produtos', composition: 'Composição' };
const themeOptions: Array<[FewTheme, string]> = [['few', 'Few Company'], ['dark', 'Few minimal'], ['caraminholas', 'Caraminholas'], ['ifight', 'iFIGHT']];
function Row({ children }: { children: ReactNode }) { return <div className="demo-row">{children}</div>; }

function Demo({ id }: { id: string }) {
  const Component = demos[id];
  if (!Component) return <p className="few-muted">Demonstração em construção.</p>;
  return <Component />;
}
function ThemeSelect({ value, onChange, label }: { value: FewTheme; onChange: (theme: FewTheme) => void; label: string }) {
  return <select aria-label={label} value={value} onChange={e => onChange(e.target.value as FewTheme)}>{themeOptions.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select>;
}
const compositionExample = `import { Dialog, Button } from '@fewcompany/ui';

<Dialog>
  <Dialog.Trigger asChild>
    <Button>Compartilhar</Button>
  </Dialog.Trigger>
  <Dialog.Content size="sm">
    <Dialog.Title>Pronto para compartilhar?</Dialog.Title>
    <Dialog.Description>Sua equipe poderá usar esta versão.</Dialog.Description>
    <Dialog.Close asChild><Button variant="secondary">Voltar</Button></Dialog.Close>
  </Dialog.Content>
</Dialog>`;

export function Catalog() {
  const searchRef = useRef<HTMLInputElement>(null);
  const [page, setPage] = useState('overview'); const [search, setSearch] = useState(''); const [theme, setTheme] = useState<FewTheme>('few'); const [menu, setMenu] = useState(false); const [copied, setCopied] = useState(false); const [copyError, setCopyError] = useState('');
  useEffect(() => { const read = () => { const id = window.location.hash.slice(1); if (specialPages.includes(id) || registry.some(item => item.id === id)) setPage(id); }; read(); window.addEventListener('hashchange', read); return () => window.removeEventListener('hashchange', read); }, []);
  useEffect(() => { const shortcut = (event: KeyboardEvent) => { if (event.key === '/' && !event.ctrlKey && !event.metaKey && !['INPUT', 'TEXTAREA', 'SELECT'].includes((event.target as HTMLElement)?.tagName)) { event.preventDefault(); setMenu(true); requestAnimationFrame(() => searchRef.current?.focus()); } if (event.key === 'Escape') setMenu(false); }; window.addEventListener('keydown', shortcut); return () => window.removeEventListener('keydown', shortcut); }, []);
  const active = registry.find(item => item.id === page);
  const matches = registry.filter(item => `${item.name} ${item.category} ${item.description} ${item.parts.join(' ')}`.toLowerCase().includes(search.toLowerCase()));
  function navigate(id: string) { setPage(id); setMenu(false); setCopied(false); setCopyError(''); window.location.hash = id; document.getElementById('main-content')?.focus(); window.scrollTo(0, 0); }
  async function copy(code: string) { try { await navigator.clipboard.writeText(code); setCopied(true); setCopyError(''); } catch { setCopyError('Selecione o trecho abaixo para copiar manualmente.'); } }
  const [framework, setFramework] = useState<Framework>('react');
  const vueSnippet = active?.vueCode ?? '';
  const usage = !active ? '' : framework === 'vue'
    ? (vueSnippet ? `${vueImportLine(vueSnippet)}\n\n${vueSnippet}` : `// Snippet Vue de ${active.name} ainda não escrito.`)
    : `import { ${active.name} } from '@fewcompany/ui';\n\n${active.code}`;
  return <div className="catalog-shell">
    <a href="#main-content" className="skip-link">Pular para o conteúdo</a>
    <aside className={`sidebar ${menu ? 'is-open' : ''}`} aria-label="Navegação do design system">
      <a className="brand" href="#overview" onClick={e => { e.preventDefault(); navigate('overview'); }}><span className="brand-word">FEW</span><span className="brand-caption">COMPANY<br />DESIGN SYSTEM</span></a>
      <label className="search"><span aria-hidden="true">⌕</span><input ref={searchRef} aria-label="Buscar componentes" placeholder="Buscar componentes…" value={search} onChange={e => setSearch(e.target.value)} /><kbd>/</kbd></label>
      <nav><p className="nav-caption">COMECE POR AQUI</p>{[['overview', 'Visão geral', '↗'], ['start', 'Instalação', '↓'], ['composition', 'Composição', '⧉'], ['tokens', 'Fundamentos', '◈']].map(([id, label, icon]) => <button type="button" key={id} onClick={() => navigate(id)} className={`nav-item ${page === id ? 'active' : ''}`} aria-current={page === id ? 'page' : undefined}><span>{icon}</span>{label}</button>)}
        <div className="nav-caption nav-count">COMPONENTES <span>{registry.length}</span></div>
        {categories.map(category => { const items = matches.filter(item => item.category === category); return items.length ? <div key={category} className="nav-group"><p>{category}</p>{items.map(item => <button type="button" key={item.id} onClick={() => navigate(item.id)} className={`nav-item component-link ${page === item.id ? 'active' : ''}`} aria-current={page === item.id ? 'page' : undefined}>{item.name}<span className="nav-dot" /></button>)}</div> : null; })}
        {!matches.length && <p className="few-muted search-empty">Nenhum componente encontrado.</p>}
        <button type="button" className={`nav-item ${page === 'apps' ? 'active' : ''}`} onClick={() => navigate('apps')}>◫ <span>Nos nossos produtos</span></button></nav>
      <div className="sidebar-footer"><span className="live-dot" /> v{LIBRARY_VERSION} <span>Composição · em evolução</span><a href="https://github.com/negra1m/desgin-system-few" target="_blank" rel="noreferrer" aria-label="Abrir repositório no GitHub">↗</a></div>
    </aside>
    <div className="catalog-content"><header className="topbar"><button className="menu-button" type="button" aria-expanded={menu} aria-label="Alternar navegação" onClick={() => setMenu(!menu)}>☰</button><div><span className="topbar-muted">Design system</span><span className="breadcrumb-slash">/</span>{active?.name ?? pageTitles[page]}</div><a href="https://fewcompany.com" target="_blank" rel="noreferrer">Feito pela Few ↗</a></header>
      <main id="main-content" tabIndex={-1}>
        {page === 'overview' && <>
          <section className="hero"><div className="hero-copy"><span className="eyebrow"><span className="live-dot" /> UMA LINGUAGEM. MUITAS POSSIBILIDADES.</span><h1>Menos repetição.<br />Mais <em>criação.</em></h1><p>Os blocos que conectam nossos produtos.<br />Compostos por partes, prontos para qualquer app React.</p><div className="hero-actions"><Button onClick={() => navigate('button')}>Explorar componentes <span aria-hidden="true">↗</span></Button><button className="text-link" onClick={() => navigate('start')}>Começar a usar <span>→</span></button></div><div className="hero-meta"><span>REACT 19</span><span>TYPESCRIPT</span><span>WEB + DESKTOP</span><span>CORE SEM FRAMEWORK</span></div></div><HeroVisual /></section>
          <section className="stats-strip" aria-label="Biblioteca"><div><strong>{registry.length}</strong><span>componentes documentados</span></div><div><strong>{String(categories.length).padStart(2, '0')}</strong><span>categorias</span></div><div><strong>02</strong><span>frameworks ao vivo: React e Vue</span></div><p>Do primeiro protótipo<br />ao produto de todo dia. ↗</p></section>
          <section className="section"><div className="section-heading"><div><span className="eyebrow">01 / PLAYGROUND</span><h2>Peças pequenas.<br className="mobile-break" /> Possibilidades grandes.</h2></div><label className="theme-select">Tema <ThemeSelect value={theme} onChange={setTheme} label="Tema do playground" /></label></div>
            <div className="playground-grid" data-few-theme={theme}><div className="preview-tile"><div className="tile-label">AÇÕES <button onClick={() => navigate('button')} aria-label="Ver Button">↗</button></div><div className="preview-body buttons-preview"><Button onClick={() => navigate('start')}>Vamos construir ↗</Button><Row><Button variant="secondary" size="sm" onClick={() => navigate('button')}>Ver variantes</Button><Button variant="ghost" size="sm" onClick={() => navigate('start')}>Saiba mais →</Button></Row></div><div className="tile-bottom"><span>Button</span><span>asChild · 5 variantes</span></div></div>
              <div className="preview-tile"><div className="tile-label">FEEDBACK <button onClick={() => navigate('badge')} aria-label="Ver Badge">↗</button></div><div className="preview-body badges-preview"><Badge tone="success" dot>Pagamento confirmado</Badge><Row><Badge tone="warning" dot>Em preparação</Badge><Badge tone="info" dot>Enviado</Badge></Row><Badge>Rascunho</Badge></div><div className="tile-bottom"><span>Badge</span><span>05 tons</span></div></div>
              <div className="preview-tile"><div className="tile-label">DADOS <button onClick={() => navigate('stat')} aria-label="Ver Stat">↗</button></div><div className="preview-body"><Stat tone="success"><Stat.Label>Projetos em movimento</Stat.Label><Stat.Value>24</Stat.Value><Stat.Change direction="up">+4 nesta semana</Stat.Change></Stat></div><div className="tile-bottom"><span>Stat</span><span>6 partes</span></div></div></div>
            <button className="all-components" onClick={() => navigate('button')}>Encontrar o próximo bloco <span>Explorar a biblioteca →</span></button>
          </section>
          <section className="section origins"><div><span className="eyebrow">02 / DA PRÁTICA PARA A BIBLIOTECA</span><h2>Nasce nos produtos.<br />Cresce com a gente.</h2><p className="section-copy">Padrões de experiências reais, organizados para os próximos projetos. A mesma base, com espaço para cada identidade.</p><button className="text-link" onClick={() => navigate('apps')}>Ver origem e adoção →</button></div><div className="origin-cards"><button onClick={() => { setTheme('caraminholas'); navigate('apps'); }} className="origin-card ceramic"><span>caraminholas.</span><small>COMÉRCIO + ATELIÊ</small><i>↗</i></button><button onClick={() => { setTheme('ifight'); navigate('apps'); }} className="origin-card fight"><span>iFIGHT<span className="fight-dot">.</span></span><small>GESTÃO + COMUNIDADE</small><i>↗</i></button></div></section>
          <section className="closing"><span className="eyebrow">BUILD WITH PURPOSE.</span><p>Seu próximo projeto<br />já tem um começo.</p><Button variant="secondary" onClick={() => navigate('start')}>Usar a biblioteca ↗</Button></section>
        </>}
        {active && <div className="document-page"><div className="doc-heading"><span className="eyebrow">{active.category.toUpperCase()} / COMPONENTES</span><Row><h1>{active.name}</h1><Badge tone="success">v{active.version}</Badge>{active.parts.length > 0 && <Badge tone="info">{active.parts.length} partes</Badge>}</Row><p>{active.description}</p></div>
          <section className="component-demo"><div className="demo-toolbar"><span>EXEMPLO INTERATIVO · {framework === 'vue' ? 'VUE' : 'REACT'}</span><div className="demo-toolbar-controls"><select aria-label="Framework da demonstração" value={framework} onChange={e => { setFramework(e.target.value as Framework); setCopied(false); }}><option value="react">React</option><option value="vue">Vue</option></select><ThemeSelect value={theme} onChange={setTheme} label="Tema do componente" /></div></div><div className="demo-canvas" data-few-theme={theme} data-framework={framework}>{framework === 'vue' ? <VueDemo key={`vue-${active.id}`} id={active.id} /> : <Demo key={active.id} id={active.id} />}</div></section>
          <section className="code-panel"><div><span>COMO USAR · {framework === 'vue' ? '@fewcompany/vue' : '@fewcompany/ui'}</span><button onClick={() => copy(usage)}>{copied ? 'Copiado ✓' : 'Copiar código'}</button></div><pre><code>{usage}</code></pre>{copyError && <p role="status">{copyError}</p>}{framework === 'vue' && !hasVueDemo(active.id) && <p className="few-muted">Demo Vue ainda não disponível para este componente.</p>}</section>
          <div className="doc-columns">
            <section><h2>Anatomia</h2>{active.parts.length ? <><Row>{active.parts.map(part => <Badge key={part}>{active.name}.{part}</Badge>)}</Row><p className="few-muted">Cada parte aceita <code>asChild</code>, <code>className</code> e as props nativas do elemento. Estado exposto por <code>data-state</code>.</p></> : <p className="few-muted">Componente simples: uma tag, com <code>asChild</code> e props nativas.</p>}<h2>Variantes e estados</h2><Row>{active.variants.map(variant => <Badge key={variant}>{variant}</Badge>)}</Row><p className="few-muted">Todas as variantes usam tokens semânticos. O tema pode ser aplicado a qualquer contêiner com <code>data-few-theme</code>.</p></section>
            <section><h2>Origem e uso</h2><p className="few-label">PADRÕES DE REFERÊNCIA</p>{active.origins.map(origin => <p key={origin} className="few-muted">↗ {origin}</p>)}{active.references.length > 0 && <><p className="few-label">INSPIRAÇÃO DE API</p><p className="few-muted">{active.references.join(' · ')}</p></>}<p className="few-label">CONSUMIDORES DO PACOTE</p><Badge tone="success">Catálogo Few · {LIBRARY_VERSION}</Badge><p className="few-muted">Caraminholas e iFIGHT ainda não importam este pacote.</p></section>
          </div></div>}
        {page === 'composition' && <div className="document-page"><div className="doc-heading"><span className="eyebrow">O PADRÃO DA BIBLIOTECA</span><h1>Composição.</h1><p>Cada componente é um conjunto de partes que você monta. Sem props gigantes, sem render-props.</p></div>
          <div className="doc-columns"><section><h2>Partes</h2><p className="section-copy"><code>Dialog</code> é a raiz. <code>Dialog.Trigger</code>, <code>Dialog.Content</code>, <code>Dialog.Title</code> são as partes. O estado mora na raiz e chega às partes por contexto, então você controla a ordem e o markup.</p><h2>asChild</h2><p className="section-copy">Qualquer parte pode virar o seu elemento: <code>{'<Dialog.Trigger asChild><Button /></Dialog.Trigger>'}</code> mescla props, classes, handlers e ref no filho. Serve para links do Next, botões próprios e ícones.</p></section>
            <section><h2>Controlado ou não</h2><p className="section-copy">Todo estado aceita <code>value / defaultValue / onValueChange</code> (ou <code>open</code>, <code>checked</code>). Sem prop, o componente se governa; com prop, você governa.</p><h2>Núcleo sem framework</h2><p className="section-copy">Cálculos, navegação por teclado e regras vivem em <code>@fewcompany/core</code>, sem DOM nem React. O adaptador React liga estado a elementos. O adaptador Vue (<code>@fewcompany/vue</code>) reusa o mesmo núcleo e o mesmo CSS: em cada componente, alterne o exemplo entre React e Vue.</p></section></div>
          <section className="code-panel"><div><span>EXEMPLO</span><button onClick={() => copy(compositionExample)}>{copied ? 'Copiado ✓' : 'Copiar código'}</button></div><pre><code>{compositionExample}</code></pre></section></div>}
        {page === 'tokens' && <div className="document-page"><div className="doc-heading"><span className="eyebrow">A BASE DE TUDO</span><h1>Fundamentos.</h1><p>Decisões pequenas que fazem nossos produtos falar a mesma língua.</p></div><h2>Paleta Few</h2><div className="swatches">{Object.entries(tokens.color).map(([name, color]) => <button className="swatch" key={name} onClick={() => copy(color)} aria-label={`Copiar ${name} ${color}`}><span style={{ background: color }} /><strong>{name}</strong><code>{color}</code></button>)}</div><p role="status" className="few-muted">{copyError || (copied ? 'Cor copiada.' : 'Clique em uma cor para copiar seu valor.')}</p><div className="doc-columns"><section><h2>Espaçamento</h2>{Object.entries(tokens.space).map(([name, value]) => <div key={name} className="token-row"><code>space.{name}</code><span style={{ width: value }} /><small>{value}</small></div>)}</section><section><h2>Tipografia</h2><p className="type-sample">Construir com propósito.</p><p className="few-muted">Poppins no catálogo, com fallback de sistema na biblioteca. Escala clara, texto legível e números tabulares.</p><h2>Movimento</h2><p className="few-muted">140 ms para feedback, 220 ms para camadas. Sem animações quando o usuário prefere movimento reduzido.</p></section></div><section className="code-panel"><div>TEMAS POR CONTÊINER</div><pre><code>{'<div data-few-theme="ifight">\n  <Button>Confirmar presença</Button>\n</div>'}</code></pre></section></div>}
        {page === 'start' && <div className="document-page"><div className="doc-heading"><span className="eyebrow">DO CATÁLOGO PARA O SEU PRODUTO</span><h1>Vamos construir.</h1><p>React no centro. Next.js, Vite, Electron ou Tauri ao redor.</p></div><Alert tone="info"><Alert.Icon /><Alert.Title>Pacotes disponíveis neste repositório</Alert.Title><Alert.Description>Dois tarballs: o núcleo e o adaptador React. Ainda não publicados no registro npm.</Alert.Description></Alert><h2>01. Gere os pacotes</h2><section className="code-panel"><pre><code>{`npm ci\nnpm run build\nnpm run pack:ui\n\n# No projeto consumidor\nnpm install /caminho/fewcompany-core-${LIBRARY_VERSION}.tgz /caminho/fewcompany-ui-${LIBRARY_VERSION}.tgz`}</code></pre></section><h2>02. Importe a base e os componentes</h2><section className="code-panel"><pre><code>{'// Next: importe o CSS em app/layout.tsx\n// Vite / desktop: importe em main.tsx\nimport "@fewcompany/ui/styles.css";\n\nimport { Button, Card } from "@fewcompany/ui";\n\n<Card>\n  <Card.Header><Card.Title>Meu primeiro cartão</Card.Title></Card.Header>\n  <Card.Content><Button>Começar</Button></Card.Content>\n</Card>'}</code></pre></section><h2>03. Escolha seu tema</h2><p className="section-copy">Use <code>data-few-theme="few"</code>, <code>dark</code>, <code>caraminholas</code> ou <code>ifight</code>. Você também pode sobrescrever as variáveis <code>--few-*</code> para uma nova marca.</p><h2>Compatibilidade</h2><DataTable caption="Onde usar" rows={[{ id: 'next', name: 'Next.js App Router', how: 'CSS no layout; interações em Client Components' }, { id: 'vite', name: 'React + Vite', how: 'CSS na entrada da aplicação' }, { id: 'desktop', name: 'Electron / Tauri com React', how: 'No renderer web; sem dependência de Node na UI' }, { id: 'vue', name: 'Vue 3.5', how: '@fewcompany/vue: mesmo core e CSS; demos ao vivo neste catálogo' }]} rowKey={row => row.id} columns={[{ key: 'name', label: 'Ambiente', render: row => row.name }, { key: 'how', label: 'Integração', render: row => row.how }]} /><p className="few-muted">React 19+. O catálogo Next e o pacote React foram verificados. Integrações desktop precisam de smoke test no aplicativo consumidor.</p></div>}
        {page === 'apps' && <div className="document-page"><div className="doc-heading"><span className="eyebrow">RASTREABILIDADE</span><h1>Uma base.<br />Várias identidades.</h1><p>Veja de onde cada padrão vem e onde esta versão da biblioteca é realmente usada.</p></div><DataTable caption="Adoção do pacote @fewcompany/ui" rows={[{ id: 'catalog', name: 'Catálogo Few', status: 'Integrado', version: LIBRARY_VERSION, tone: 'success' }, { id: 'caraminholas', name: 'Caraminholas', status: 'Referência · migração pendente', version: '—', tone: 'warning' }, { id: 'ifight', name: 'iFIGHT', status: 'Referência · migração pendente', version: '—', tone: 'warning' }]} rowKey={row => row.id} columns={[{ key: 'name', label: 'Produto', render: row => row.name }, { key: 'version', label: 'Versão instalada', render: row => row.version }, { key: 'status', label: 'Adoção', render: row => <Badge tone={row.tone as Tone}>{row.status}</Badge> }]} /><h2>O que trouxemos da prática</h2><div className="doc-columns"><Card><Card.Header><Card.Title>Caraminholas</Card.Title><Card.Description>Checkout, conteúdo e operações</Card.Description></Card.Header><Card.Content><p className="few-muted">Hierarquia de formulários, resumo de pedidos, cartões, mensagens de erro e estados administrativos.</p><Badge>Origem de padrões</Badge></Card.Content></Card><Card><Card.Header><Card.Title>iFIGHT</Card.Title><Card.Description>Painéis, dados e comunidade</Card.Description></Card.Header><Card.Content><p className="few-muted">Variantes de botão, estados semânticos, números tabulares, indicadores e superfícies em tema escuro.</p><Badge>Origem de padrões</Badge></Card.Content></Card></div><h2>Publicação npm</h2><p className="section-copy">Viável como infraestrutura interna: um pacote versionado reduz cópia de código e permite atualizações previsíveis. A recomendação é distribuir os tarballs localmente e validar a adoção em dois produtos antes de abrir uma oferta pública. Leia o parecer completo em <a href="https://github.com/negra1m/desgin-system-few/blob/main/docs/npm-strategy.md">docs/npm-strategy.md ↗</a>.</p></div>}
      </main><footer className="footer"><span className="footer-brand">FEW</span><span>Purpose shapes direction.</span><a href="https://github.com/negra1m/desgin-system-few">Código, decisões e próximos passos ↗</a><span>© 2026 Few Company</span></footer></div>
  </div>;
}
