"use client";
import { useEffect, useRef, useState, type ReactNode } from 'react';
import { Alert, Avatar, Badge, Button, Card, CardHeader, Checkbox, DataTable, Dialog, EmptyState, Field, Input, MetricCard, Progress, Select, Skeleton, Switch, Tabs, Textarea, registry, tokens, type FewTheme, type Tone } from '@fewcompany/ui';

const categories = ['Ações','Formulários','Feedback','Dados','Estrutura'];
const specialPages = ['overview','tokens','start','apps'];
const orders = [{ id: 'CAR-0042', name: 'Ana Lima', value: 'R$ 224,90', status: 'Pago', tone: 'success' }, { id: 'CAR-0041', name: 'João Santos', value: 'R$ 180,00', status: 'Em preparação', tone: 'warning' }, { id: 'CAR-0040', name: 'Bia Costa', value: 'R$ 320,00', status: 'Enviado', tone: 'info' }];
function Row({ children }: { children: ReactNode }) { return <div className="demo-row">{children}</div>; }

function Demo({ id }: { id: string }) {
  const [tab, setTab] = useState('overview'); const [open, setOpen] = useState(false); const [enabled, setEnabled] = useState(true); const [value, setValue] = useState(72); const [saved, setSaved] = useState(false);
  const [busy, setBusy] = useState(false);
  async function save() { setBusy(true); await new Promise(resolve => setTimeout(resolve, 700)); setBusy(false); setSaved(true); }
  if (id === 'button') return <div className="demo-stack"><Row><Button onClick={save} loading={busy}>{saved ? 'Salvo ✓' : 'Salvar alterações'}</Button><Button variant="secondary" onClick={() => setSaved(false)}>Restaurar</Button><Button variant="ghost">Ver detalhes ↗</Button><Button variant="danger" onClick={() => setSaved(false)}>Remover</Button></Row><Row><Button size="sm">Pequeno</Button><Button size="md">Padrão</Button><Button size="lg">Confortável</Button><Button disabled>Indisponível</Button><Button loading>Processando</Button></Row><p className="few-muted" role="status">{saved ? 'Alterações salvas nesta demonstração.' : 'Clique em salvar para testar o carregamento.'}</p></div>;
  if (id === 'badge') return <Row>{(['neutral','success','warning','danger','info'] as Tone[]).map((tone,i) => <Badge key={tone} tone={tone}>{['Rascunho','Confirmado','Pendente','Recusado','Em análise'][i]}</Badge>)}</Row>;
  if (id === 'card') return <div className="demo-grid"><Card><CardHeader title="Um lugar para cada ideia" description="Organize o que importa." action={<Badge>Rascunho</Badge>} /><p className="few-muted">Uma superfície neutra, com espaço para o seu produto respirar.</p><Button variant="secondary" onClick={() => setSaved(!saved)}>{saved ? 'Projeto aberto ✓' : 'Explorar projeto ↗'}</Button></Card><MetricCard label="Projetos em movimento" value="08" change="+2 nesta semana" tone="success" /></div>;
  if (id === 'input') return <div className="demo-grid"><Field label="E-mail" hint="Usado para confirmações e atualizações.">{props => <Input {...props} type="email" placeholder="voce@fewcompany.com" />}</Field><Field label="Nome do projeto" error="Dê um nome ao seu projeto.">{props => <Input {...props} placeholder="Meu próximo projeto" />}</Field></div>;
  if (id === 'select') return <div className="demo-narrow"><Field label="Situação do pedido" hint="Selecione a próxima etapa.">{props => <Select {...props}><option>Em preparação</option><option>Enviado</option><option>Entregue</option></Select>}</Field></div>;
  if (id === 'textarea') return <Field label="Sua próxima ideia" hint="Até 500 caracteres.">{props => <Textarea {...props} maxLength={500} placeholder="O que vamos construir juntos?" />}</Field>;
  if (id === 'checkbox') return <div className="demo-stack"><Checkbox label="Receber atualizações do projeto" defaultChecked /><Checkbox label="Incluir na biblioteca compartilhada" /><Checkbox label="Disponível em breve" disabled /></div>;
  if (id === 'switch') return <div className="demo-stack"><Switch label="Notificações por e-mail" checked={enabled} onChange={e => setEnabled(e.target.checked)} /><p className="few-muted" role="status">Notificações {enabled ? 'ativadas' : 'desativadas'} nesta demonstração.</p><Switch label="Preferência indisponível" disabled /></div>;
  if (id === 'alert') return <div className="demo-stack"><Alert tone="danger" title="O cartão não foi aprovado" action={<Button variant="secondary" size="sm" onClick={() => setSaved(true)}>{saved ? 'Pix selecionado ✓' : 'Usar Pix'}</Button>}>O banco não autorizou esta compra. Revise os dados ou escolha outra forma de pagamento.</Alert><Alert tone="success" title="Tudo certo por aqui">Seu pedido foi salvo. Você pode acompanhar as próximas etapas.</Alert><Alert tone="warning" title="Falta só um detalhe">Complete seu endereço para continuar.</Alert></div>;
  if (id === 'tabs') return <Tabs value={tab} onValueChange={setTab} items={[{ id:'overview',label:'Visão geral',content:<p className="few-muted">Todas as informações do projeto em um só lugar.</p> },{id:'activity',label:'Atividade',content:<p className="few-muted">Ana atualizou os componentes há 2 minutos.</p>},{id:'settings',label:'Configurações',content:<Switch label="Publicar atualizações" defaultChecked />}]} />;
  if (id === 'dialog') return <><Button onClick={() => setOpen(true)}>Abrir diálogo ↗</Button><Dialog open={open} onOpenChange={setOpen} title="Pronto para compartilhar?" description="Sua equipe poderá usar os componentes desta versão."><Row><Button onClick={() => { setSaved(true); setOpen(false); }}>Confirmar</Button><Button variant="secondary" onClick={() => setOpen(false)}>Voltar</Button></Row></Dialog>{saved && <p className="few-muted" role="status">Compartilhamento confirmado nesta demonstração.</p>}</>;
  if (id === 'metric') return <div className="demo-grid"><MetricCard label="Receita do mês" value="R$ 12.480" change="+12% neste mês" tone="success" /><MetricCard label="Alunos ativos" value="148" change="8 novas matrículas" tone="info" /></div>;
  if (id === 'table') return <DataTable caption="Pedidos recentes · dados de exemplo" rows={orders} rowKey={row => row.id} columns={[{key:'id',label:'Pedido',render:row => row.id},{key:'name',label:'Cliente',render:row => row.name},{key:'value',label:'Total',render:row => row.value},{key:'status',label:'Situação',render:row => <Badge tone={row.tone as Tone}>{row.status}</Badge>}]} />;
  if (id === 'empty') return saved ? <Alert tone="success" title="Seu primeiro projeto foi criado" action={<Button variant="secondary" onClick={() => setSaved(false)}>Recomeçar</Button>}>Este é um exemplo local, sem salvar dados.</Alert> : <EmptyState title="Tudo começa com uma ideia" description="Ainda não há projetos por aqui. Que tal criar o primeiro?" action={<Button onClick={() => setSaved(true)}>+ Novo projeto</Button>} />;
  if (id === 'skeleton') return <div role="status" aria-label="Carregando conteúdo" className="demo-stack"><Skeleton width="36%" height={22} /><Skeleton width="80%" /><Skeleton width="64%" /><Skeleton height={100} /></div>;
  if (id === 'progress') return <div className="demo-stack"><Progress label="Configuração do perfil" value={value} /><label className="few-muted">Ajustar progresso <input aria-label="Ajustar progresso" type="range" min="0" max="100" value={value} onChange={e => setValue(Number(e.target.value))} /></label></div>;
  if (id === 'avatar') return <Row><Avatar name="Ana Lima" size="sm" /><Avatar name="João Santos" /><Avatar name="Few Company" size="lg" /><span className="few-muted">Pessoas por trás de cada produto.</span></Row>;
  return null;
}

export function Catalog() {
  const searchRef = useRef<HTMLInputElement>(null);
  const [page, setPage] = useState('overview'); const [search, setSearch] = useState(''); const [theme, setTheme] = useState<FewTheme>('few'); const [menu, setMenu] = useState(false); const [copied, setCopied] = useState(false); const [copyError, setCopyError] = useState('');
  useEffect(() => { const read = () => { const id = window.location.hash.slice(1); if (specialPages.includes(id) || registry.some(item => item.id === id)) setPage(id); }; read(); window.addEventListener('hashchange', read); return () => window.removeEventListener('hashchange', read); }, []);
  useEffect(() => { const shortcut = (event: KeyboardEvent) => { if (event.key === '/' && !event.ctrlKey && !event.metaKey && !['INPUT','TEXTAREA','SELECT'].includes((event.target as HTMLElement)?.tagName)) { event.preventDefault(); setMenu(true); searchRef.current?.focus(); } if (event.key === 'Escape') setMenu(false); }; window.addEventListener('keydown', shortcut); return () => window.removeEventListener('keydown', shortcut); }, []);
  const active = registry.find(item => item.id === page);
  const matches = registry.filter(item => `${item.name} ${item.category} ${item.description}`.toLowerCase().includes(search.toLowerCase()));
  function navigate(id: string) { setPage(id); setMenu(false); setCopied(false); setCopyError(''); window.location.hash = id; document.getElementById('main-content')?.focus(); window.scrollTo(0,0); }
  async function copy(code: string) { try { await navigator.clipboard.writeText(code); setCopied(true); setCopyError(''); } catch { setCopyError('Selecione o trecho abaixo para copiar manualmente.'); } }
  return <div className="catalog-shell">
    <a href="#main-content" className="skip-link">Pular para o conteúdo</a>
    <aside className={`sidebar ${menu ? 'is-open' : ''}`} aria-label="Navegação do design system">
      <a className="brand" href="#overview" onClick={e => {e.preventDefault();navigate('overview');}}><span className="brand-word">few<span>®</span></span><span className="brand-caption">COMPANY<br />DESIGN SYSTEM</span></a>
      <label className="search"><span aria-hidden="true">⌕</span><input ref={searchRef} aria-label="Buscar componentes" placeholder="Buscar componentes…" value={search} onChange={e => setSearch(e.target.value)} /><kbd>/</kbd></label>
      <nav><p className="nav-caption">COMECE POR AQUI</p>{[['overview','Visão geral','↗'],['start','Instalação','↓'],['tokens','Fundamentos','◈']].map(([id,label,icon]) => <button type="button" key={id} onClick={() => navigate(id)} className={`nav-item ${page === id ? 'active' : ''}`} aria-current={page === id ? 'page' : undefined}><span>{icon}</span>{label}</button>)}
      <div className="nav-caption nav-count">COMPONENTES <span>{registry.length}</span></div>
      {categories.map(category => { const items = matches.filter(item => item.category === category); return items.length ? <div key={category} className="nav-group"><p>{category}</p>{items.map(item => <button type="button" key={item.id} onClick={() => navigate(item.id)} className={`nav-item component-link ${page === item.id ? 'active' : ''}`} aria-current={page === item.id ? 'page' : undefined}>{item.name}<span className="nav-dot" /></button>)}</div> : null; })}
      {!matches.length && <p className="few-muted search-empty">Nenhum componente encontrado.</p>}
      <button type="button" className={`nav-item ${page === 'apps' ? 'active' : ''}`} onClick={() => navigate('apps')}>◫ <span>Nos nossos produtos</span></button></nav>
      <div className="sidebar-footer"><span className="live-dot" /> v0.1.0 <span>MVP · em evolução</span><a href="https://github.com/negra1m/desgin-system-few" target="_blank" rel="noreferrer" aria-label="Abrir repositório no GitHub">↗</a></div>
    </aside>
    <div className="catalog-content"><header className="topbar"><button className="menu-button" type="button" aria-expanded={menu} aria-label="Alternar navegação" onClick={() => setMenu(!menu)}>☰</button><div><span className="topbar-muted">Design system</span><span className="breadcrumb-slash">/</span>{active?.name ?? ({overview:'Visão geral',tokens:'Fundamentos',start:'Instalação',apps:'Produtos'}[page])}</div><a href="https://fewcompany.com" target="_blank" rel="noreferrer">Feito pela Few ↗</a></header>
    <main id="main-content" tabIndex={-1}>
      {page === 'overview' && <>
        <section className="hero"><div className="hero-copy"><span className="eyebrow"><span className="live-dot" /> UMA LINGUAGEM. MUITAS POSSIBILIDADES.</span><h1>Menos repetição.<br />Mais <em>criação.</em></h1><p>Os blocos que conectam nossos produtos.<br />Pensados na prática. Feitos para construir juntos.</p><div className="hero-actions"><Button onClick={() => navigate('button')}>Explorar componentes <span aria-hidden="true">↗</span></Button><button className="text-link" onClick={() => navigate('start')}>Começar a usar <span>→</span></button></div><div className="hero-meta"><span>REACT 19</span><span>TYPESCRIPT</span><span>WEB + DESKTOP</span></div></div><div className="hero-art" aria-hidden="true"><span className="art-label">FEW / BUILDING BLOCKS</span><div className="art-grid"><i /><i /><i /><i /></div><span className="art-caption">Purpose shapes direction.<br /><span>Est. 2026 — v0.1</span></span><span className="art-plus">+</span></div></section>
        <section className="stats-strip" aria-label="Biblioteca"><div><strong>{registry.length}</strong><span>componentes documentados</span></div><div><strong>04</strong><span>temas para experimentar</span></div><div><strong>01</strong><span>linguagem compartilhada</span></div><p>Do primeiro protótipo<br />ao produto de todo dia. ↗</p></section>
        <section className="section"><div className="section-heading"><div><span className="eyebrow">01 / PLAYGROUND</span><h2>Peças pequenas.<br className="mobile-break" /> Possibilidades grandes.</h2></div><label className="theme-select">Tema <select value={theme} onChange={e => setTheme(e.target.value as FewTheme)}><option value="few">Few Company</option><option value="dark">Few escuro</option><option value="caraminholas">Caraminholas</option><option value="ifight">iFIGHT</option></select></label></div>
          <div className="playground-grid" data-few-theme={theme}><div className="preview-tile"><div className="tile-label">AÇÕES <button onClick={() => navigate('button')} aria-label="Ver Button">↗</button></div><div className="preview-body buttons-preview"><Button onClick={() => navigate('start')}>Vamos construir ↗</Button><Row><Button variant="secondary" size="sm" onClick={() => navigate('button')}>Ver variantes</Button><Button variant="ghost" size="sm" onClick={() => navigate('start')}>Saiba mais →</Button></Row></div><div className="tile-bottom"><span>Button</span><span>08 variantes</span></div></div>
          <div className="preview-tile"><div className="tile-label">FEEDBACK <button onClick={() => navigate('badge')} aria-label="Ver Badge">↗</button></div><div className="preview-body badges-preview"><Badge tone="success">Pagamento confirmado</Badge><Row><Badge tone="warning">Em preparação</Badge><Badge tone="info">Enviado</Badge></Row><Badge>Rascunho</Badge></div><div className="tile-bottom"><span>Badge</span><span>05 variantes</span></div></div>
          <div className="preview-tile"><div className="tile-label">DADOS <button onClick={() => navigate('metric')} aria-label="Ver MetricCard">↗</button></div><div className="preview-body"><p className="few-label">PROJETOS EM MOVIMENTO</p><div className="mini-metric">24<span>↗</span></div><Badge tone="success">+4 nesta semana</Badge></div><div className="tile-bottom"><span>MetricCard</span><span>03 variantes</span></div></div></div>
          <button className="all-components" onClick={() => navigate('button')}>Encontrar o próximo bloco <span>Explorar a biblioteca →</span></button>
        </section>
        <section className="section origins"><div><span className="eyebrow">02 / DA PRÁTICA PARA A BIBLIOTECA</span><h2>Nasce nos produtos.<br />Cresce com a gente.</h2><p className="section-copy">Padrões de experiências reais, organizados para os próximos projetos. A mesma base, com espaço para cada identidade.</p><button className="text-link" onClick={() => navigate('apps')}>Ver origem e adoção →</button></div><div className="origin-cards"><button onClick={() => {setTheme('caraminholas');navigate('apps');}} className="origin-card ceramic"><span>caraminholas.</span><small>COMÉRCIO + ATELIÊ</small><i>↗</i></button><button onClick={() => {setTheme('ifight');navigate('apps');}} className="origin-card fight"><span>iFIGHT<span className="fight-dot">.</span></span><small>GESTÃO + COMUNIDADE</small><i>↗</i></button></div></section>
        <section className="closing"><span className="eyebrow">BUILD WITH PURPOSE.</span><p>Seu próximo projeto<br />já tem um começo.</p><Button variant="secondary" onClick={() => navigate('start')}>Usar a biblioteca ↗</Button></section>
      </>}
      {active && <div className="document-page"><div className="doc-heading"><span className="eyebrow">{active.category.toUpperCase()} / COMPONENTES</span><Row><h1>{active.name}</h1><Badge tone="success">v{active.version}</Badge></Row><p>{active.description}</p></div><section className="component-demo"><div className="demo-toolbar"><span>EXEMPLO INTERATIVO</span><select aria-label="Tema do componente" value={theme} onChange={e => setTheme(e.target.value as FewTheme)}><option value="few">Few Company</option><option value="dark">Few escuro</option><option value="caraminholas">Caraminholas</option><option value="ifight">iFIGHT</option></select></div><div className="demo-canvas" data-few-theme={theme}><Demo key={active.id} id={active.id} /></div></section><section className="code-panel"><div><span>COMO USAR</span><button onClick={() => copy(`import { ${active.name} } from '@fewcompany/ui';\n\n${active.code}`)}>{copied ? 'Copiado ✓' : 'Copiar código'}</button></div><pre><code>{`import { ${active.name} } from '@fewcompany/ui';\n\n${active.code}`}</code></pre>{copyError && <p role="status">{copyError}</p>}</section><div className="doc-columns"><section><h2>Variantes e estados</h2><Row>{active.variants.map(variant => <Badge key={variant}>{variant}</Badge>)}</Row><p className="few-muted">Todas as variantes usam tokens semânticos. O tema pode ser aplicado a qualquer contêiner com <code>data-few-theme</code>.</p></section><section><h2>Origem e uso</h2><p className="few-label">PADRÕES DE REFERÊNCIA</p>{active.origins.map(origin => <p key={origin} className="few-muted">↗ {origin}</p>)}<p className="few-label">CONSUMIDORES DO PACOTE</p><Badge tone="success">Catálogo Few · 0.1.0</Badge><p className="few-muted">Caraminholas e iFIGHT ainda não importam este pacote.</p></section></div></div>}
      {page === 'tokens' && <div className="document-page"><div className="doc-heading"><span className="eyebrow">A BASE DE TUDO</span><h1>Fundamentos.</h1><p>Decisões pequenas que fazem nossos produtos falar a mesma língua.</p></div><h2>Paleta Few</h2><div className="swatches">{Object.entries(tokens.color).map(([name,color]) => <button className="swatch" key={name} onClick={() => copy(color)} aria-label={`Copiar ${name} ${color}`}><span style={{background:color}} /><strong>{name}</strong><code>{color}</code></button>)}</div><p role="status" className="few-muted">{copyError || (copied ? 'Cor copiada.' : 'Clique em uma cor para copiar seu valor.')}</p><div className="doc-columns"><section><h2>Espaçamento</h2>{Object.entries(tokens.space).map(([name,value]) => <div key={name} className="token-row"><code>space.{name}</code><span style={{width:value}} /><small>{value}</small></div>)}</section><section><h2>Tipografia</h2><p className="type-sample">Construir com propósito.</p><p className="few-muted">Sans-serif de sistema na biblioteca. Escala clara, texto legível e números tabulares. O catálogo usa a hierarquia editorial e o verde profundo da Few.</p><h2>Movimento</h2><p className="few-muted">140 ms para feedback. Sem animações quando o usuário prefere movimento reduzido.</p></section></div><section className="code-panel"><div>TEMAS POR CONTÊINER</div><pre><code>{'<div data-few-theme="ifight">\n  <Button>Confirmar presença</Button>\n</div>'}</code></pre></section></div>}
      {page === 'start' && <div className="document-page"><div className="doc-heading"><span className="eyebrow">DO CATÁLOGO PARA O SEU PRODUTO</span><h1>Vamos construir.</h1><p>React no centro. Next.js, Vite, Electron ou Tauri ao redor.</p></div><Alert title="MVP disponível neste repositório" tone="info">O pacote está pronto para empacotar e instalar localmente. Ainda não foi publicado no registro npm.</Alert><h2>01. Gere o pacote</h2><section className="code-panel"><pre><code>{'npm ci\nnpm run build\nnpm run pack:ui\n\n# No projeto consumidor\nnpm install /caminho/fewcompany-ui-0.1.0.tgz'}</code></pre></section><h2>02. Importe a base e os componentes</h2><section className="code-panel"><pre><code>{'// Next: importe o CSS em app/layout.tsx\n// Vite / desktop: importe em main.tsx\nimport "@fewcompany/ui/styles.css";\n\nimport { Button, Card } from "@fewcompany/ui";\n\n<Card>\n  <Button>Meu primeiro componente</Button>\n</Card>'}</code></pre></section><h2>03. Escolha seu tema</h2><p className="section-copy">Use <code>data-few-theme="few"</code>, <code>dark</code>, <code>caraminholas</code> ou <code>ifight</code>. Você também pode sobrescrever as variáveis <code>--few-*</code> para uma nova marca.</p><h2>Compatibilidade</h2><DataTable caption="Onde usar" rows={[{id:'next',name:'Next.js App Router',how:'CSS no layout; interações em Client Components'},{id:'vite',name:'React + Vite',how:'CSS na entrada da aplicação'},{id:'desktop',name:'Electron / Tauri com React',how:'No renderer web; sem dependência de Node na UI'}]} rowKey={row => row.id} columns={[{key:'name',label:'Ambiente',render:row => row.name},{key:'how',label:'Integração',render:row => row.how}]} /><p className="few-muted">React 19+. O catálogo Next e o pacote React foram verificados neste MVP. Integrações desktop precisam de smoke test no aplicativo consumidor.</p></div>}
      {page === 'apps' && <div className="document-page"><div className="doc-heading"><span className="eyebrow">RASTREABILIDADE</span><h1>Uma base.<br />Várias identidades.</h1><p>Veja de onde cada padrão vem e onde esta versão da biblioteca é realmente usada.</p></div><DataTable caption="Adoção do pacote @fewcompany/ui" rows={[{id:'catalog',name:'Catálogo Few',status:'Integrado',version:'0.1.0',tone:'success'},{id:'caraminholas',name:'Caraminholas',status:'Referência · migração pendente',version:'—',tone:'warning'},{id:'ifight',name:'iFIGHT',status:'Referência · migração pendente',version:'—',tone:'warning'}]} rowKey={row => row.id} columns={[{key:'name',label:'Produto',render:row => row.name},{key:'version',label:'Versão instalada',render:row => row.version},{key:'status',label:'Adoção',render:row => <Badge tone={row.tone as Tone}>{row.status}</Badge>}]} /><h2>O que trouxemos da prática</h2><div className="doc-columns"><Card><CardHeader title="Caraminholas" description="Checkout, conteúdo e operações" /><p className="few-muted">Hierarquia de formulários, resumo de pedidos, cartões, mensagens de erro e estados administrativos.</p><Badge>Origem de padrões</Badge></Card><Card><CardHeader title="iFIGHT" description="Painéis, dados e comunidade" /><p className="few-muted">Variantes de botão, estados semânticos, números tabulares, indicadores e superfícies em tema escuro.</p><Badge>Origem de padrões</Badge></Card></div><h2>Publicação npm</h2><p className="section-copy">Viável como infraestrutura interna: um pacote versionado reduz cópia de código e permite atualizações previsíveis. A recomendação para o MVP é distribuir o pacote localmente e validar sua adoção em dois produtos antes de abrir uma oferta pública. Leia o parecer completo em <a href="https://github.com/negra1m/desgin-system-few/blob/main/docs/npm-strategy.md">docs/npm-strategy.md ↗</a>.</p></div>}
    </main><footer className="footer"><span className="footer-brand">few.</span><span>Purpose shapes direction.</span><a href="https://github.com/negra1m/desgin-system-few">Código, decisões e próximos passos ↗</a><span>© 2026 Few Company</span></footer></div>
  </div>;
}
