export interface ComponentRecord {
  id: string; name: string; category: 'Ações' | 'Formulários' | 'Feedback' | 'Dados' | 'Estrutura'; description: string;
  version: string; variants: string[]; origins: string[]; consumers: string[]; code: string;
}
const component = (id: string, name: string, category: ComponentRecord['category'], description: string, variants: string[], origins: string[], code: string): ComponentRecord => ({ id, name, category, description, variants, origins, code, version: '0.2.0', consumers: ['Catálogo Few'] });
export const registry: ComponentRecord[] = [
  component('button','Button','Ações','Uma ação clara, em cada contexto. Estados de carregamento e desabilitado fazem parte do componente.',['primary','secondary','ghost','danger','sm','md','lg','loading'],['Caraminholas · .btn','iFIGHT · ui/button.tsx'],'<Button variant="primary" onClick={save}>Salvar alterações</Button>'),
  component('badge','Badge','Feedback','Status legíveis, com cor e texto. Nunca dependa apenas da cor para comunicar.',['neutral','success','warning','danger','info'],['Caraminholas · .chip','iFIGHT · ui/badge.tsx'],'<Badge tone="success">Pagamento confirmado</Badge>'),
  component('card','Card','Estrutura','Superfícies para agrupar informações com uma hierarquia tranquila.',['default','com CardHeader'],['Caraminholas · .card','iFIGHT · ui/card.tsx'],'<Card><CardHeader title="Resumo" description="Pedido #0042" /><p>Seu conteúdo aqui.</p></Card>'),
  component('input','Input','Formulários','Entrada nativa com foco visível, estados inválidos e suporte a autocomplete.',['default','disabled','invalid'],['Caraminholas · .field','iFIGHT · formulários'],'<Field label="E-mail" hint="Enviaremos sua confirmação.">{props => <Input {...props} type="email" autoComplete="email" />}</Field>'),
  component('select','Select','Formulários','Seleção nativa para opções curtas, com navegação de teclado e suporte mobile.',['default','disabled'],['Caraminholas · OrderForm'],'<Field label="Situação">{props => <Select {...props}><option>Em preparação</option><option>Enviado</option></Select>}</Field>'),
  component('textarea','Textarea','Formulários','Espaço para mensagens, descrições e observações.',['default','invalid'],['Caraminholas · FormRow'],'<Field label="Observações">{props => <Textarea {...props} placeholder="Escreva aqui…" />}</Field>'),
  component('checkbox','Checkbox','Formulários','Permissões e escolhas independentes com um alvo de clique confortável.',['checked','unchecked','disabled'],['Caraminholas · configurações'],'<Checkbox label="Receber atualizações por e-mail" defaultChecked />'),
  component('switch','Switch','Formulários','Ative ou desative uma preferência de efeito imediato.',['on','off','disabled'],['iFIGHT · preferências'],'<Switch label="Notificações" checked={enabled} onChange={e => setEnabled(e.target.checked)} />'),
  component('alert','Alert','Feedback','Explique o que aconteceu e ofereça um próximo passo útil.',['info','success','warning','danger'],['Caraminholas · feedback de checkout','iFIGHT · cards de status'],'<Alert tone="danger" title="O cartão não foi aprovado" action={<Button variant="secondary">Usar Pix</Button>}>Confira a autorização no app do banco.</Alert>'),
  component('tabs','Tabs','Estrutura','Agrupe vistas relacionadas. Use setas, Home e End para navegar pelo teclado.',['controlled','keyboard'],['iFIGHT · navegação de painéis'],'<Tabs value={tab} onValueChange={setTab} items={[{ id: "overview", label: "Resumo", content: <p>Visão geral</p> }]} />'),
  component('dialog','Dialog','Estrutura','Uma decisão por vez. Modal nativo, foco contido e fechamento com Escape.',['controlled','native modal'],['Caraminholas · StageDialog'],'<Dialog open={open} onOpenChange={setOpen} title="Confirmar envio"><Button onClick={() => setOpen(false)}>Confirmar</Button></Dialog>'),
  component('metric','MetricCard','Dados','Um indicador, seu contexto e uma variação. Valores com números tabulares.',['neutral','success','warning'],['iFIGHT · Visão da Academia'],'<MetricCard label="Receita do mês" value="R$ 12.480" change="+12% no mês" tone="success" />'),
  component('table','DataTable','Dados','Dados tabulares com legenda, cabeçalhos semânticos e rolagem horizontal.',['populated','empty'],['Caraminholas · pedidos','iFIGHT · alunos'],'<DataTable caption="Pedidos recentes" rows={orders} rowKey={row => row.id} columns={[{ key: "name", label: "Cliente", render: row => row.name }]} />'),
  component('empty','EmptyState','Feedback','Explique a ausência de dados e dê um caminho para começar.',['with action','informational'],['Caraminholas · sacola vazia'],'<EmptyState title="Tudo começa com uma ideia" description="Crie seu primeiro projeto." action={<Button>Novo projeto</Button>} />'),
  component('skeleton','Skeleton','Feedback','Reserve espaço durante o carregamento. Respeita a preferência por movimento reduzido.',['text','block'],['Few · novo padrão'],'<div role="status" aria-label="Carregando conteúdo"><Skeleton width="60%" /><Skeleton height={120} /></div>'),
  component('progress','Progress','Feedback','Progresso mensurável com rótulo e valor numérico acessíveis.',['0–100','clamped'],['iFIGHT · progressão'],'<Progress label="Configuração do perfil" value={72} />'),
  component('avatar','Avatar','Dados','Identificação por iniciais, sem depender de serviços externos de imagem.',['sm','md','lg'],['iFIGHT · alunos'],'<Avatar name="Ana Lima" size="md" />'),
];
