import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
const load = createRequire(import.meta.url);
const { chromium } = load(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base = process.env.TEST_BASE_URL || 'http://127.0.0.1:3200';
const browser = await chromium.launch({ headless:true });
try {
  const page = await browser.newPage({ viewport:{width:1440,height:1000} });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(base); await page.getByRole('heading',{name:/Menos repetição/}).waitFor();
  mkdirSync('artifacts',{recursive:true});
  await page.screenshot({path:'artifacts/catalog-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Explorar componentes'}).click();
  await page.getByRole('button',{name:'Salvar alterações',exact:true}).click();
  await page.getByRole('button',{name:'Salvo ✓',exact:true}).waitFor();
  await page.getByLabel('Tema do componente').selectOption('ifight');
  assert.equal(await page.locator('.demo-canvas').getAttribute('data-few-theme'),'ifight');
  await page.getByLabel('Buscar componentes').fill('dialog');
  assert.ok(await page.locator('.component-link').count() >= 1);
  await page.getByRole('button',{name:'Dialog',exact:true}).click();
  await page.getByRole('button',{name:'Abrir diálogo'}).click();
  await page.getByRole('dialog').waitFor();
  await page.keyboard.press('Escape');
  await page.getByRole('dialog').waitFor({state:'hidden'});
  assert.ok(await page.getByRole('button',{name:'Abrir diálogo'}).evaluate(element => element === document.activeElement));
  await page.getByLabel('Buscar componentes').fill('');
  await page.getByRole('button',{name:'Tabs',exact:true}).click();
  await page.getByRole('tab',{name:'Visão geral',exact:true}).focus();
  await page.keyboard.press('ArrowRight');
  assert.equal(await page.getByRole('tab',{name:'Atividade'}).getAttribute('aria-selected'),'true');
  await page.goto(`${base}/#table`); await page.getByRole('table').waitFor();
  await page.setViewportSize({width:390,height:844});
  await page.goto(base); await page.getByRole('heading',{name:/Menos repetição/}).waitFor();
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({path:'artifacts/catalog-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'Alternar navegação'}).click();
  await page.getByRole('button',{name:'Input',exact:true}).click();
  await page.getByLabel('E-mail',{exact:true}).fill('teste@fewcompany.com');
  assert.equal(await page.getByLabel('E-mail',{exact:true}).inputValue(),'teste@fewcompany.com');
  assert.equal(await page.getByLabel('Campo inválido').getAttribute('aria-invalid'),'true');
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  assert.deepEqual(errors,[]);
  console.log('PASS: static export, navigation, search, loading, themes, modal focus/Escape, tabs keyboard, deep link, form associations and mobile.');
} finally { await browser.close(); }
